### ISSUE TITLE
Add historical list of reentrancy attacks

### ISSUE THREAD

**Issue by pcaversaccio** [immunefi-team/Web3-Security-Library#10]
Feel free to add my [A Historical Collection of Reentrancy Attacks](https://github.com/pcaversaccio/reentrancy-attacks) repo to your reentrancy attack section. It provides for each attack the post-mortem/detailed explanation, the victim & attack contract as well as the attack transaction.

**Comment by pepin-immunefi** [comment]
Done, thanks!
