### ISSUE TITLE
Section Request - Sketchy Web3 BBPs

### ISSUE THREAD

**Issue by xyizko** [immunefi-team/Web3-Security-Library#36]
# What ?

Recommendation to populate a similar list like this - [`https://github.com/pdelteil/scammy-bbp`](https://github.com/pdelteil/scammy-bbp)

# Why ? 

Could serve to be an excellent resource to detect questionable behavior

**Comment by janbro** [comment]
There are a few other repositories out there already tracking something like this that are already being maintained by others, I don't want to convolute this repository with that information. This repository is intended to provide the tools and resources for someone to get started in web3 security.
